height: 500
menubar: false
toolbar:
  - undo redo | formatselect | bold italic backcolor | link | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat | table | code | uploadimage | help
plugins:
  - advlist autolink lists link charmap preview anchor
  - searchreplace visualblocks code fullscreen
  - insertdatetime media table code help wordcount
  - table
  - code
  - link
  - media
